import React, { Component } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import Autocomplete from "./AutoComplete";

export default class MedicationList extends Component {
  constructor() {
    super();
    this.state = {
      product: "",
      medication: "test",
      message: ""
    };
  }
  changeHandler = e => {
    this.setState({ [e.target.name]: e.target.value });
  };

  getMedicationResult = e => {
    e.preventDefault();
    const { product, medication } = this.state;
    const pSplit = product.split(', ')
    const carrier = pSplit[0]
    const product2 = pSplit[1]
    console.log(carrier, product2)
    axios
      .post("https://insurance-risk-assesment.herokuapp.com/api/meds/", {prescription: medication.toLocaleLowerCase(), carrier: carrier, product2: product2})
      .then(res => {
        console.log(res.data[0].outcome);
      })
      .catch(err => {
        console.log(err);
      });
  };

  putMedOnState = (e, input) => {
    // e.preventDefault();
    e.persist();
    this.setState({ medication: input });
    console.log("fired");
  };

  render() {
    return (
      <div className="med-list">
        <div className="back-button-container">
          <Link to="/">
            <button className="back-button">back</button>
          </Link>
        </div>
        <form className="input-container" onSubmit={this.getMedicationResult}>
          <label htmlFor="Product" />
          <select name="product" value={this.state.product} className="input" onChange={this.changeHandler}>
            <option className="medication-select">Choose Product</option>
            {products.map(prod => {
              return (
                <option key={prod.carrier + prod.product2} value={`${prod.carrier}, ${prod.product2}`} className="medication-select">
                  {prod.carrier} {prod.product2}
                </option>
              )
            })}
            />
          </select>
          <Autocomplete suggestions={suggestions} putMedOnState={this.putMedOnState} />

          <button>Check Medication</button>
        </form>
      </div>
    );
  }
}

const products = [
  { carrier: "CFG", product2: "Dignified Choice" },
  { carrier: "CFG", product2: "Term" },
  { carrier: "Foresters", product2: "PlanRight" },
  { carrier: "MOO", product2: "Living Promise" },
  { carrier: "MOO", product2: "Term" },
  { carrier: "Phoenix", product2: "Remembrance" },
  { carrier: "Phoenix", product2: "Safe Harbor" },
  { carrier: "Transamerica", product2: "Solutions" }
];

const suggestions = [
  "Abilify",
  "Abraxane",
  "Accupril",
  "Accuretic",
  "Acebutolol HCL",
  "Aceon",
  "Acetyl L-Carnitine",
  "Actiq",
  "Activase",
  "Actoplus",
  "Actos",
  "Adalat",
  "Adriamycin",
  "Adrucil",
  "Advair",
  "Afinitor",
  "Agenerase",
  "Aggrastat",
  "Aggrenox",
  "Agrylin",
  "Akineton",
  "Albuterol",
  "Aldactazide",
  "Aldactone",
  "Aldomat",
  "Alimta",
  "Alkeran",
  "Allopurinol",
  "Aloxi",
  "Alprazolam",
  "Altace",
  "Amantadine HCL",
  "Amaryl",
  "Ambisome",
  "Amifostine",
  "Amiloride HCL",
  "Amlodipine",
  'Besylate/Benaz"',
  "Amyl Nitrate",
  "Anagrelide HCL",
  "Angiomax",
  "Antabuse",
  "Anastrozole",
  "Anoro Ellipta",
  "Anzemet",
  "Aptivus",
  "Apokyn",
  "Apresoline",
  "Aranesp",
  "Arcapta Neohaler",
  "Aredia",
  "Argatroban",
  "Aricept",
  "Arimidex",
  "Aromasin",
  "Arranon",
  "Arsenic Trioxide",
  "Arzerra",
  "Atacand",
  "Atamet",
  "Atenolol",
  "Atgam",
  "Ativan",
  "Atripla",
  '"Atrovent/Atrovent',
  "HFA",
  'Atrovent (Nasal)"',
  "Avalide",
  "Avandia",
  "Avapro",
  "Avastin",
  "Avonex",
  "Azilect",
  "Azasan",
  "Azathioprine",
  "Azmacort",
  "Azor",
  "Baclofen",
  "Baraclude",
  "Benazepril HCL",
  "Benicar",
  "Benlysta",
  '"Benztropine Mesylate"',
  "Betapace",
  "Betaseron",
  "Betaxolol HCL",
  "Bexxar",
  "Bicnu",
  "BiDil",
  "Bisoprolol Fumarate",
  "Blenoxane",
  "Bleomycin Sulphate",
  "Blocadren",
  "Brevibloc",
  "Brovana",
  "Breo Ellipta",
  '"Bromocriptine Mesylate"',
  "Bumetadine",
  "Bumex",
  "Buprenex",
  "Busulflex",
  "Bystolic",
  "Calcijex",
  "Calcitriol",
  "Calcium Acetate",
  "Calan",
  "Campath",
  "Campral",
  "Camptosar",
  "Capoten",
  "Capozide",
  "Captopril",
  "Carbamazepine",
  "Carbatrol",
  "Carbidopa",
  "Carboplatin",
  "Cardioplegic",
  "Cardizem",
  "Cardura",
  "Carnitor",
  "Cartia",
  "Cartrol",
  "Carvedilol",
  "Catapress",
  "Casodex",
  "CeeNu",
  "Celebrex",
  "Cellcept",
  "Cerubidine",
  "Cesamet",
  "Chlorambucil",
  "Chlorpromazine",
  "Cisplatin",
  "Citalopram",
  "Cladribine",
  "Clolar",
  "Clopidogrel",
  "Cogentin",
  "Cognex",
  "Combivent",
  "Combivir",
  "Complera",
  "Comtan",
  "Copaxone",
  "Copegus",
  "Cordarone",
  "Coreg",
  "Corgard",
  "Cosmegen",
  "Coumadin",
  "Cozaar",
  "Crixivan",
  "Cyclophosphamide",
  "Cyclosporine",
  "Cyclosporine Modified",
  "Cystagon",
  "Cytarabine",
  "Cytogam",
  "Cytosar-U",
  "Cytovene",
  "Cytoxan",
  "Dacarbazine",
  "Dacogen",
  "Dactinomycin",
  "Daliresp",
  "Daunorubicin HCL",
  "Daunoxome",
  "Demadex",
  "Depacon",
  "Depade",
  "Depakene",
  "Depakote",
  "Depocyt",
  "Dexrazoxane",
  "Diabeta",
  "Diabinese",
  "Diazoxide",
  "Didanosine",
  "Digitek",
  "Digoxin",
  "Dilacor",
  "Dilantin",
  "Dilatrate SR",
  "Dilor",
  "Diltiazem",
  "Diovan",
  "Disulfiram",
  "Dolophine",
  "Donepezil HCL",
  "Doxil",
  "Doxorubicin HCL",
  "Dronabinol",
  "DTIC-Dome",
  "Duoneb",
  "Dyazide",
  "Dynacirc",
  "Dyrenium",
  "Edecrin",
  "Edurant",
  "Eldepryl",
  "Eligard",
  "Eliphos",
  "Elitek",
  "Ellence",
  "Eloxatin",
  "Elspar",
  "Emcyt",
  "Emend",
  "Emtriva",
  "Enalapril Maleate",
  "Enalaprilat",
  "Epitol",
  "Epivir",
  "Epizicom",
  "Eplerenone",
  "Erbitux",
  "Ergoloid Mesylates",
  "Eskalith",
  "Esmolol HCL",
  "Estinyl",
  "Ethyol",
  "Etopophos",
  "Etoposide",
  "Eulexin",
  "Evista",
  "Exelon",
  "Exforge",
  "Fareston",
  "Farxiga",
  "Faslodex",
  "Felodipine",
  "Femara",
  "Fentanyl Citrate",
  "Fentora",
  "Floxuridine",
  "Fludara",
  "Fludarabine Phosphate",
  "Fluoxymesterone",
  "Flutamide",
  "Folotyn",
  "Fortamet",
  "Fortovase",
  "Foscarnet Sodium",
  "Foscavir",
  "Fosinopril Sodium",
  "Fosrenol",
  "Fortesta",
  "FUDR",
  "Furosemide",
  "Fusilev",
  "Fuzeon",
  "Gabapentin",
  "Gabitril",
  "Galantamine",
  "Gallium Nitrate",
  "Ganciclovir",
  "Ganite",
  "Gemzar",
  "Gengraf",
  "Gleevec",
  "Gliadel Wafer",
  "Glipizide",
  "Glucophage",
  "Glucotrol",
  "Glyburide",
  "Glynase",
  "Granisetron HCL",
  "Granisol",
  "Halaven",
  "Haldol",
  "Haloperidol",
  "Halotestin",
  "HCTZ",
  "HCTZ/Triamterene",
  "Hectoral",
  "Heparin",
  "Hepsera",
  "Herceptin",
  "Hexalen",
  "Hivid",
  "Humalog",
  "Humulin",
  "Hycamtin",
  "Hydralazine HCL",
  "Hydrea",
  "Hydroxyurea",
  "Hydergine",
  "Hydroxychloroquine",
  "Hyperstat IV",
  "Hytrin",
  "Hyzaar",
  "Idamycin PFS",
  "Idarubicin",
  "Ifex",
  '"Ifex/Mesnex Combo',
  'Pack"',
  "Ifosfamide",
  "Iletin",
  "Imdur",
  "Imuran",
  "Inamrinone",
  "Inderal",
  "Inderide",
  "Infergen",
  "Innopran XL",
  "Inspra",
  "Insulin",
  "Intelence",
  "Intron-A",
  "Invirase",
  "Invokana",
  "Ipratropium Bromide",
  "Iressa",
  "Irinotecan",
  "Ismo",
  "Isochron",
  "Isodax",
  "Isoptin",
  "Isordil",
  "Isosorbide",
  "Dinitrate/Mononitrate",
  "Ixempra",
  "Janumet",
  "Januvia",
  "Jardiance",
  "Jetvana",
  "Kaletra",
  "Kemadrin",
  "Kepivance",
  "Kerlone",
  "Kytril",
  "Labetaolol",
  "Lamictal",
  "Lamtrogine",
  "Lanoxicaps",
  "Lanoxin",
  "Lantus",
  "Lasix",
  "Larodopa",
  "Leucovorin Calcium",
  "Leukeran",
  "Leukine",
  "Leuprolide",
  "Leustatin",
  "Levatol",
  "Levodopa",
  "Levamisole HCL",
  "Levemir",
  "Levocarnitine",
  "Lexiva",
  "Lexxel",
  "Lipitor",
  "Lisinopril",
  "Lithium",
  "Lodosyn",
  "Lopressor",
  "Losartan Potassium",
  "Lotensin",
  "Lotrel",
  "Loxapine",
  "Loxitane",
  "Lozol",
  "Lupron",
  "Lyrica",
  "Lysodren",
  "Lytensopril",
  "Marinol",
  "Matulane",
  "Maxzide",
  "Mavik",
  "Mellaril",
  "Melphalan",
  'Hydrochloride"',
  "Mepron",
  "Mercaptopurine",
  "Mesna",
  "Mesnex",
  "Metformin",
  "Methadone",
  "Methadose",
  "Methotrexate",
  "Methyldopa",
  "Metolazone",
  '"Metoprolol',
  'Tartrate/Succinate"',
  "Metoprolol HCTZ",
  "Mevacor",
  "Micardis",
  "Micronase",
  "Midamor",
  "Milrinone",
  "Minipress",
  "Minitran",
  "Mirapex",
  "Mithracin",
  "Mitomycin",
  "Mitoxantrone HCL",
  "Moban",
  "Moduretic",
  "Moexipril HCL",
  "Monoket",
  "Monopril",
  "Mustargen",
  "Mutamycin",
  "Mycobutin",
  "Myfortic",
  "Mykrok",
  "Myleran",
  "Mylocel",
  "Mylotarg",
  "Mysoline",
  "Nadolol",
  "Namenda",
  "Narcan",
  "Naloxone",
  "Naltrexone",
  "Natrecor",
  "Navane",
  "Navelbine",
  "Nebupent",
  "Neosar",
  "Neulasta",
  "Neumega",
  "Neupro",
  "Neurontin",
  "Neutrexin",
  "Nexavar",
  "Nifedipine",
  "Nilandron",
  "Nimodipine",
  "Nimotop",
  "Nipent",
  "Nitrek",
  "Nitro-bid",
  "Nitro-dur",
  '"Nitroglycerine/Nitrota',
  'b/Nitroquick/Nitrostat"',
  "Nitrol",
  "Nitromist",
  "Nolvadex",
  "Normodyne",
  "Norpace",
  "Norvasc",
  "Norvir",
  "Novolin",
  "Novolog",
  "Novanitrone",
  "Noxafil",
  "Octreotide Acetate",
  "Oforta",
  "Olanzapine",
  "Olysio",
  "Omontys",
  "Oncaspar",
  "Ondansetron",
  "Onsolis",
  "Ontak",
  "Onxol",
  "Orthoclone OKT3",
  "Oseni",
  "Pacerone",
  "Paclitaxel",
  "Pamidronate Disodium",
  "Panretin",
  "Paraplatin",
  "Parcopa",
  "Parlodel",
  "Paxil",
  "Pentam 300",
  "PentamidineIsethionate",
  "Pentostatin",
  "Pegasys",
  "Peg-Intron",
  "Pepcid",
  "Pergolide Mesylate",
  "Perindopril Erbumine",
  "Permax",
  "Phenobarbital",
  "Phoslo",
  "Photofrin",
  "Pindolol",
  "Plaquenil",
  "Platinol AQ",
  "Plavix",
  "Plegisol",
  "Plenaxis",
  "Plendil",
  "Prandin",
  "Pravachol",
  "Prazosin",
  "Prezista",
  "Primacor",
  "Prinivil",
  "Prinzide",
  "Procardia",
  "Prograf",
  "Proleukin",
  "Prolixin",
  "Propanolol HCL",
  "Provenge",
  "Proventil",
  "Prozac",
  "Purinethol",
  "Quadramet",
  "Quetiapine",
  "Quinapril",
  "Quinaretic",
  "Ramipril",
  "Ranexa",
  "Ranitidine",
  "Rapamune",
  "Razadyne",
  "Rebetol",
  "Rebetron",
  "Rebif",
  "Reglan",
  "Requip",
  "Reminyl",
  "Renagel",
  "Renvela",
  "Rescriptor",
  "Retrovir",
  "Revex",
  "Revia",
  "Revlimid",
  "Reyataz",
  "Ribapak",
  "Ribasphere",
  "Ribatab",
  "Ribavirin",
  "Rilutek",
  "Risperdal",
  "Risperidone",
  "Rituxan",
  "Rivastigmine Tartrate",
  "Rocaltrol",
  "Roferon",
  "Ropinirole",
  "Rubex",
  "Rythmol",
  "Sancuso",
  "Sandimmune",
  "Sandostatin",
  "Saquinavir Mesylate",
  "Sectral",
  "Selegiline HCL",
  "Selzentry",
  "Sensipar",
  "Serevent",
  "Seroquel",
  "Simvastatin",
  "Simulect",
  "Sinemet/Sinemet CR",
  "Sodium Edecrin",
  "Soltalol Hydrochloride",
  "Soltamox",
  "Sorine",
  "Sotalol HCL",
  "Spiriva",
  "Spironolactone",
  "Sprycel",
  "Stalevo",
  "Starlix",
  "Stilphostrol",
  "Striverdi Respimat",
  "Sublimaze",
  "Suboxone",
  "Subutex",
  "Sustiva",
  "Sutent",
  "Symbicort",
  "Symmetrel",
  "Tabloid",
  "Tagamet",
  "Tambocor",
  "Tamoxifen",
  "Tarceva",
  "Targretin",
  "Tarka",
  "Tasigna",
  "Tasmar",
  "Taxol",
  "Taxotere",
  "Tegretol",
  "Temodar",
  "Tenex",
  "Tenoretic",
  "Tenormin",
  "Teslac",
  "Teveten",
  "Thalomid",
  "Theodur",
  "Theophylline",
  "Theracys",
  "Thioplex",
  "Thioridazine",
  "Thiotepa",
  "Thiothixene",
  "Thymoglobulin",
  "Thorazine",
  "Tiazac",
  "Tice BCG",
  "Ticlid",
  "Tilade",
  "Timolide",
  "Timolol Maleate",
  "Tolazamide",
  "Tolbutamide",
  "Tolinase",
  "Toposar",
  "Topotecan",
  "Totect",
  "Torisel",
  "Torsemide",
  "Toprol XL",
  "Trandate",
  "Trandolapril",
  "Treanda",
  "Trelstar",
  "Tretinoin",
  "Triamterene",
  "Triamterene/HCTZ",
  "Tribenzor",
  "Trisenox",
  "Trihexyphenidyl HCL",
  "Trizivir",
  "Truvada",
  "Twynsta",
  "Tykerb",
  "Tyzeka",
  "Uniretic",
  "Univasc",
  "Uvadex",
  "Valcyte",
  "Valproic Acid",
  "Valstar",
  "Valturna",
  "Vascor",
  "Vaseretic",
  "Vasotec",
  "Velcade",
  "Ventolin",
  "Vepisid",
  "Verapamil",
  "Vesanoid",
  "Viadur",
  "Viaspan",
  "Victrelis",
  "Vidaza",
  "Videx",
  "Vinblastine Sulfate",
  "Vincasar PFS",
  "Vincristine Sulfate",
  "Vinorelbine Tartrate",
  "Viracept",
  "Viramune",
  "Viread",
  "Visken",
  "Vistide",
  "Vivitrol",
  "Votrient",
  "Vumon",
  "Warfarin",
  "Xeloda",
  "Xgeva",
  "Xopenex",
  "Zanosar",
  "Zantac",
  "Zaroxolyn",
  "Zebeta",
  "Zelapar",
  "Zenapax",
  "Zemplar",
  "Zerit",
  "Zestoretic",
  "Zestril",
  "Zevalin Y-90",
  "Ziac",
  "Ziagen",
  "Zidovudine",
  "Zinecard",
  "Zocor",
  "Zofran",
  "Zoladex",
  "Zolinza",
  "Zoloft",
  "Zometa",
  "Zortress",
  "Zuplenz",
  "Zyprexa"
];
